from typing import List, Tuple, Optional


def reservoire_test() -> Tuple[List[float], List[List[float]]]: ...
def test_frame() -> None: ...

class Reservoire():
    def __init__(self) -> None: ...
    def test_run(self) -> Optional[Tuple[List, List]]: ...

class RCModel():
    def __init__(self) -> None: ...
    def test_reservoire(self) -> None: ...
